from pathlib import Path
import subprocess,os,json,time,hashlib
w=Path(__file__).resolve().parent.parent;el=w/'electrical';m=w/'manufacturing';v=w/'verification';m.mkdir(exist_ok=True);name='Anticipy_R1_E1_PROTOTYPE';pcb=el/(name+'.kicad_pcb');sch=el/(name+'.kicad_sch');cli='/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli';env=dict(os.environ,KICAD_CONFIG_HOME=str(w/'kicad-config'),KICAD10_FOOTPRINT_DIR='/Applications/KiCad/KiCad.app/Contents/SharedSupport/footprints',KICAD10_SYMBOL_DIR='/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();hashes={p.name:sha(p)for p in el.iterdir() if p.suffix in ('.kicad_pcb','.kicad_sch','.kicad_pro','.kicad_dru','.kicad_sym')}
commands=[('assembly_top',['pcb','export','pdf','--mode-single','--layers','F.Fab,Edge.Cuts','--exclude-value','--black-and-white','--crossout-DNP-footprints-on-fab-layers','--scale','4','-o',str(m/'Assembly_top.pdf'),str(pcb)]),('assembly_bottom',['pcb','export','pdf','--mode-single','--layers','B.Fab,Edge.Cuts','--exclude-value','--black-and-white','--mirror','--scale','4','-o',str(m/'Assembly_bottom.pdf'),str(pcb)]),('schematic',['sch','export','pdf','-o',str(m/'Schematic.pdf'),str(sch)]),('gerbers_saved_fills',['pcb','export','gerbers','--layers','F.Cu,In1.Cu,In2.Cu,B.Cu,F.Mask,B.Mask,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,Edge.Cuts','--subtract-soldermask','-o',str(m/'gerbers')+'/',str(pcb)]),('drills',['pcb','export','drill','--excellon-separate-th','--generate-map','--generate-report','--map-format','pdf','--report-path',str(m/'drill_report.txt'),'-o',str(m/'drill')+'/',str(pcb)]),('positions',['pcb','export','pos','--format','csv','--units','mm','--side','both','--exclude-dnp','-o',str(m/'Placement.csv'),str(pcb)]),('ipc356',['pcb','export','ipcd356','-o',str(m/'Connectivity.ipc'),str(pcb)]),('copper_pdf',['pcb','export','pdf','--mode-multipage','--layers','F.Cu,In1.Cu,In2.Cu,B.Cu','--common-layers','Edge.Cuts','--scale','0','-o',str(m/'Copper_layers.pdf'),str(pcb)])]
rows=[]
for tag,args in commands:
 assert all(sha(el/n)==h for n,h in hashes.items()),'Source changed mid export; stop for re-verification'
 start=time.monotonic()
 try:r=subprocess.run([cli]+args,env=env,capture_output=True,text=True,timeout=50);rc=r.returncode;log=r.stdout+r.stderr
 except subprocess.TimeoutExpired as e:rc='timeout';log=str(e)
 (v/(tag+'.log')).write_text(log);rows.append(dict(task=tag,command=[cli]+args,returncode=rc,elapsed_seconds=round(time.monotonic()-start,3)));(v/'export_receipt.json').write_text(json.dumps(dict(source_sha256=hashes,source_unchanged=all(sha(el/n)==h for n,h in hashes.items()),zone_basis='Saved copper independently verified by native DRC; refill is separate evidence.',commands=rows),indent=2)+'\n');print(tag,rc,flush=True)
 if rc!=0:raise SystemExit(1)
